---
# - name: Initialize Kubernetes master with kubeadm init.
#   command: >
#     kubeadm init
#     --pod-network-cidr={{ kubernetes_pod_network.cidr }}
#     --apiserver-advertise-address={{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }}
#     --kubernetes-version {{ kubernetes_version }}
#     --ignore-preflight-errors={{ kubernetes_ignore_preflight_errors }}
#     {{ kubernetes_kubeadm_init_extra_opts }}
#   register: kubeadmin_init

- name: Init Kubernetes cluster
  shell: |
    kubeadm init \
    --service-cidr {{ kubernetes_service_cidr }} \
    --kubernetes-version {{ kubernetes_version }} \
    --pod-network-cidr {{ kubernetes_pod_network.cidr}} \
    --apiserver-advertise-address={{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }} \
    {{ kubernetes_kubeadm_init_extra_opts  }}
  register: kubeadmin_init

- name: Print the init output to screen.
  debug:
    var: kubeadmin_init.stdout
    verbosity: 2
#  when: not kubernetes_init.stat.exists

- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    state: directory
    mode: 0755

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644

- name: Configure Calico networking.
  command: "{{ item }}"
  with_items:
    - kubectl apply -f {{ kubernetes_calico_manifest_file }}
  register: calico_result
  changed_when: "'created' in calico_result.stdout"
  when: kubernetes_pod_network.cni == 'calico'