galaxy_info:
  role_name: kubernetes/cni
  author: Philip Welz
  description: Role for applying the CNI on the Kuberentes Master
  company: na
  license: "license (BSD, MIT, APACHE)"
  min_ansible_version: 2.10
  platforms:
    - name: Debian
      versions:
        - buster
    - name: Ubuntu
      versions:
        - focal